apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
spec:
  description: Dev Project for Wil's Application
  sourceRepos:
    - 'https://github.com/Ghilphar/*'
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
