Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine317"
  config.vm.synced_folder "./", "/vagrant"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.define "fgaribotS" do |fgaribotS|
    fgaribotS.vm.hostname = "fgaribotS"
    fgaribotS.vm.network "private_network", ip: "192.168.56.110"
    fgaribotS.vm.provision "shell", path: './scripts/nodeS_pods.sh'
    fgaribotS.vm.provision "shell", path: './scripts/deploy_apps.sh', run: "always"
    #fgaribotS.vm.provision "shell", inline: <<-SHELL
    #  # Install K3s in server mode
    #  # waiting for eth1 to be configured
    #  while true; do
    #    IP=$(ip addr show eth1 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)
    #    if [[ "$IP" == "192.168.56.110" ]]; then
    #        break
    #    fi
    #    echo "Waiting for eth1 to be configured..."
    #    sleep 5
    #  done
    #  curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --flannel-iface=eth1 --write-kubeconfig-mode 644" sh -
    #SHELL
  end
end
