Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine317"
  config.vm.synced_folder "./", "/vagrant"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.define "fgaribotS" do |fgaribotS|
    fgaribotS.vm.hostname = "fgaribotS"
    fgaribotS.vm.network "private_network", ip: "192.168.56.110"
    fgaribotS.vm.provision "shell", path: './scripts/nodeS_pods.sh'
    fgaribotS.vm.provision "shell", path: './scripts/deploy_apps.sh', run: "always"
  end
end
