Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine317"
  config.vm.synced_folder "./", "/vagrant"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  
  config.vm.define "fgaribotS" do |fgaribotS|
    fgaribotS.vm.hostname = "fgaribotS"
    fgaribotS.vm.network "private_network", ip: "192.168.56.110"
    fgaribotS.vm.provision "shell", path: './scripts/server.sh'
  end

  config.vm.define "fgaribotSW" do |fgaribotSW|
    fgaribotSW.vm.hostname = "fgaribotSW"
    fgaribotSW.vm.network "private_network", ip: "192.168.56.111"
    fgaribotSW.vm.provision "shell", path: './scripts/worker.sh'
  end
end
